# Generated by Django 2.0.6 on 2018-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestame', models.CharField(max_length=20)),
                ('host_ip', models.CharField(max_length=20)),
                ('cpu_percent', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestame', models.CharField(max_length=20)),
                ('host_ip', models.CharField(max_length=20)),
                ('disk_percent', models.CharField(max_length=20)),
                ('disk_free', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestame', models.CharField(max_length=20)),
                ('host_ip', models.CharField(max_length=20)),
                ('mem_percent', models.CharField(max_length=20)),
                ('mem_free', models.CharField(max_length=20)),
            ],
        ),
    ]
