# Generated by Django 2.0.6 on 2018-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='cpu_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='timestame',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diskdata',
            name='disk_free',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diskdata',
            name='disk_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diskdata',
            name='timestame',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='memorydata',
            name='mem_free',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='memorydata',
            name='mem_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorydata',
            name='timestame',
            field=models.IntegerField(),
        ),
    ]
