# Generated by Django 2.0.6 on 2019-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_lastcomm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskdata',
            name='disk_free',
            field=models.BigIntegerField(),
        ),
    ]
