# Generated by Django 2.0.6 on 2019-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_auto_20190129_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskdata',
            name='disk_free',
            field=models.BigIntegerField(),
        ),
    ]
