# Generated by Django 2.0.6 on 2019-02-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_threvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threvalue',
        ),
    ]
