# Generated by Django 2.2.1 on 2019-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_delete_threvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcomm',
            name='host_name',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
