# Generated by Django 2.2.1 on 2019-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_lastcomm_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcomm',
            name='alarm_rule',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
