# Generated by Django 2.0.6 on 2019-02-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thre_name', models.CharField(max_length=20)),
                ('thre_value', models.CharField(max_length=200)),
            ],
        ),
    ]
