# Generated by Django 2.0.6 on 2019-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_auto_20190420_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='threvalue',
            name='thre_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
